services:
  movielist-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: movielist-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  movielist-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: movielist-test
    environment:
      - NODE_ENV=test
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - testing
    command: npm test

networks:
  default:
    name: movielist-network
